apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: web
          image: quay.io/ravindra_be2004/mydemo:v1
          ports:
            - name: web
              containerPort: 8080
          volumeMounts:
            - name: web 
              mountPath: /tmp/demo1
  volumeClaimTemplates:
    - metadata:
        name: web
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "lvms-vg1"
        resources:
          requests:
            storage: 1Gi
